
twitter:
    consumer_key: your-token-here
    consumer_secret: your-token-here
    access_token: your-token-here
    access_token_secret: your-token-here

discord: 
    token: 'your-token-here'

acrcloud:
    host: identify-eu-west-1.acrcloud.com
    token: your-token-here
    secret_token: your-token-here
